--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('FishLNet2_pb')

ROLEINFO = protobuf.Descriptor();
ROLEINFO_NAME_FIELD = protobuf.FieldDescriptor();
ROLEINFO_SEX_FIELD = protobuf.FieldDescriptor();
ROLEINFO_LEVEL_FIELD = protobuf.FieldDescriptor();

ROLEINFO_NAME_FIELD.name = "name"
ROLEINFO_NAME_FIELD.full_name = ".FishProto2.RoleInfo.name"
ROLEINFO_NAME_FIELD.number = 2
ROLEINFO_NAME_FIELD.index = 0
ROLEINFO_NAME_FIELD.label = 2
ROLEINFO_NAME_FIELD.has_default_value = false
ROLEINFO_NAME_FIELD.default_value = ""
ROLEINFO_NAME_FIELD.type = 9
ROLEINFO_NAME_FIELD.cpp_type = 9

ROLEINFO_SEX_FIELD.name = "sex"
ROLEINFO_SEX_FIELD.full_name = ".FishProto2.RoleInfo.sex"
ROLEINFO_SEX_FIELD.number = 3
ROLEINFO_SEX_FIELD.index = 1
ROLEINFO_SEX_FIELD.label = 2
ROLEINFO_SEX_FIELD.has_default_value = false
ROLEINFO_SEX_FIELD.default_value = 0
ROLEINFO_SEX_FIELD.type = 5
ROLEINFO_SEX_FIELD.cpp_type = 1

ROLEINFO_LEVEL_FIELD.name = "level"
ROLEINFO_LEVEL_FIELD.full_name = ".FishProto2.RoleInfo.level"
ROLEINFO_LEVEL_FIELD.number = 4
ROLEINFO_LEVEL_FIELD.index = 2
ROLEINFO_LEVEL_FIELD.label = 2
ROLEINFO_LEVEL_FIELD.has_default_value = false
ROLEINFO_LEVEL_FIELD.default_value = 0
ROLEINFO_LEVEL_FIELD.type = 5
ROLEINFO_LEVEL_FIELD.cpp_type = 1

ROLEINFO.name = "RoleInfo"
ROLEINFO.full_name = ".FishProto2.RoleInfo"
ROLEINFO.nested_types = {}
ROLEINFO.enum_types = {}
ROLEINFO.fields = {ROLEINFO_NAME_FIELD, ROLEINFO_SEX_FIELD, ROLEINFO_LEVEL_FIELD}
ROLEINFO.is_extendable = false
ROLEINFO.extensions = {}

RoleInfo = protobuf.Message(ROLEINFO)

